##################################################
# Makefile
##################################################
ENTRYPOINT=0x30400
ASM=nasm
CC=gcc
ASMFLAGS=-I include/ -f elf
CCFLAGS= -I include/  -c -fno-builtin -m32 -std=c99  -fno-stack-protector  
LD=ld
LDFLAFS = -T kernel.lds
BOOT:=boot.asm
LDR:=loader.asm
KERNEL:=kernel.asm
BOOT_BIN:=$(subst .asm,.bin,$(BOOT))
LDR_BIN:=$(subst .asm,.bin,$(LDR))
KERNEL_BIN:=$(subst .asm,.bin,$(KERNEL))
OBJECTS = kernel.o init.o memory.o exception.o schdule.o gate.o page.o
IMG:=a.img
FLOPPY:=/mnt/floppy/

.PHONY : everything

everything : $(BOOT_BIN) $(LDR_BIN) $(KERNEL_BIN)
	dd if=$(BOOT_BIN) of=$(IMG) bs=512 count=1 conv=notrunc
	sudo mount -o loop $(IMG) $(FLOPPY)
	sudo cp $(LDR_BIN) $(FLOPPY) -v
	sudo cp $(KERNEL_BIN) $(FLOPPY) -v
	sudo umount $(FLOPPY)

clean :
	rm -f $(BOOT_BIN) $(LDR_BIN) $(KERNEL_BIN) *.o

$(BOOT_BIN) : $(BOOT)
	nasm $< -o $@

$(LDR_BIN) : $(LDR)
	nasm $< -o $@

$(KERNEL_BIN) : $(OBJECTS)
	$(LD) $(LDFLAGS) -o $(KERNEL_BIN) $(OBJECTS)
kernel.o:kernel.asm
	$(ASM) $(ASMFLAGS) -o $@ $<
test.o: test.c
	$(CC)  $(CCFLAGS) -o $@ $<
init.o: init.c
	$(CC)  $(CCFLAGS) -o $@ $<
memory.o: memory.c
	$(CC)  $(CCFLAGS) -o $@ $<
exception.o: exception.c
	$(CC)  $(CCFLAGS) -o $@ $<
schdule.o: schdule.c
	$(CC)  $(CCFLAGS) -o $@ $<
gate.o: gate.c
	$(CC)  $(CCFLAGS) -o $@ $<
page.o: page.c
	$(CC)  $(CCFLAGS) -o $@ $<
	
	
	
